language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - npm install

script:
    - npm run apidocs

deploy:
    provider: script
    script: npm run apidocs-deploy
    skip_cleanup: true
    on:
        branch: master
